name: publish package

on:
  release:
    types:
      - published

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"

      - name: Install dependency
        run: npm ci

      - name: Run build
        run: npm run sass:build

      - name: Minify build
        run: npm run sass:minify

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  publish_package:
    needs: [build]
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:

      - name: Publish
        run: npm run publishToNPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}